name: Terraform Azure VM Deploy

on:
  workflow_dispatch:

jobs:

  terraform-init:

    name: Terraform Init
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Environment/dev

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

  terraform-plan:

    name: Terraform Plan
    runs-on: ubuntu-latest

    needs: terraform-init

    defaults:
      run:
        working-directory: ./Environment/dev

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

  terraform-apply:

    name: Terraform Apply
    runs-on: ubuntu-latest

    needs: terraform-plan

    environment:
      name: production

    defaults:
      run:
        working-directory: ./Environment/dev

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
